# -*- coding: utf-8 -*-
"""Content-monetisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1za-XKPEG_lGkayJvJCLtGH5zKF15HvKi
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("youtube_ad_revenue_dataset.csv")
df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

import matplotlib.pyplot as plt

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.boxplot(df['likes'].dropna())
plt.title("Likes")

plt.subplot(1,3,2)
plt.boxplot(df['comments'].dropna())
plt.title("Comments")

plt.subplot(1,3,3)
plt.boxplot(df['watch_time_minutes'].dropna())
plt.title("Watch Time")

plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(15,4))

plt.subplot(1,3,1)
plt.scatter(df['views'], df['likes'])
plt.title("Views vs Likes")

plt.subplot(1,3,2)
plt.scatter(df['views'], df['comments'])
plt.title("Views vs Comments")

plt.subplot(1,3,3)
plt.scatter(df['views'], df['watch_time_minutes'])
plt.title("Views vs Watch Time")

plt.show()

df['likes'].fillna(df['likes'].median(), inplace=True)
df['comments'].fillna(df['comments'].median(), inplace=True)
df['watch_time_minutes'].fillna(df['watch_time_minutes'].median(), inplace=True)

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()

df.duplicated().sum()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

import matplotlib.pyplot as plt

plt.hist(df['ad_revenue_usd'], bins=50)
plt.title("Distribution of Ad Revenue")
plt.show()

df.groupby('category')['ad_revenue_usd'].mean().sort_values(ascending=False)

df.groupby('device')['ad_revenue_usd'].mean().sort_values(ascending=False)

df.groupby('country')['ad_revenue_usd'].mean().sort_values(ascending=False)

df.groupby('country')['views'].mean().sort_values(ascending=False)
df.groupby('category')['subscribers'].mean().sort_values(ascending=False)

df.groupby('category')['subscribers'].mean().sort_values(ascending=False)

import matplotlib.pyplot as plt

plt.scatter(df['watch_time_minutes'], df['ad_revenue_usd'])
plt.title("Watch Time vs Revenue")
plt.xlabel("Watch Time")
plt.ylabel("Revenue")
plt.show()

df['engagement_rate'] = (df['likes'] + df['comments']) / df['views']
df.head()

df['engagement_rate'].describe()

df[['engagement_rate','ad_revenue_usd']].corr()

df['likes_per_view'] = df['likes'] / df['views']
df['comments_per_view'] = df['comments'] / df['views']
df['watch_time_per_view'] = df['watch_time_minutes'] / df['views']
df['views_per_subscriber'] = df['views'] / df['subscribers']
df.head()

df[['likes_per_view','comments_per_view','watch_time_per_view','views_per_subscriber']].describe()

df[['likes_per_view','comments_per_view','watch_time_per_view','views_per_subscriber']].corr()

df.isnull().sum().sum()

df_model = df.copy()

df_model = pd.get_dummies(df_model, columns=['category','device','country'], drop_first=True)

df_model

X = df_model[['views','likes','comments','watch_time_minutes',
              'video_length_minutes','subscribers']]

y = df_model['ad_revenue_usd']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("R2 Score:", r2)
print("RMSE:", rmse)
print("MAE:", mae)

df['ad_revenue_usd'].describe()

coefficients = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
print(coefficients.sort_values(by='Coefficient', ascending=False))

from sklearn.linear_model import Ridge

ridge = Ridge()
ridge.fit(X_train_scaled, y_train)

y_pred_ridge = ridge.predict(X_test_scaled)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

print("R2 Score:", r2_score(y_test, y_pred_ridge))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_ridge)))
print("MAE:", mean_absolute_error(y_test, y_pred_ridge))

from sklearn.linear_model import Lasso

lasso = Lasso()
lasso.fit(X_train_scaled, y_train)

y_pred_lasso = lasso.predict(X_test_scaled)

print("R2 Score:", r2_score(y_test, y_pred_lasso))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lasso)))
print("MAE:", mean_absolute_error(y_test, y_pred_lasso))

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)   # Trees do NOT need scaling

y_pred_dt = dt.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred_dt))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_dt)))
print("MAE:", mean_absolute_error(y_test, y_pred_dt))

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))

import pickle

pickle.dump(model, open("revenue_model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

import pandas as pd

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

coefficients = coefficients.sort_values(by="Coefficient", ascending=False)
coefficients.head(10)

import matplotlib.pyplot as plt

top_features = coefficients.head(10)

plt.figure(figsize=(8,5))
plt.barh(top_features["Feature"], top_features["Coefficient"])
plt.gca().invert_yaxis()
plt.title("Top Features Influencing Ad Revenue")
plt.show()

from google.colab import files
files.download("revenue_model.pkl")
files.download("scaler.pkl")

