# -*- coding: utf-8 -*-
"""Music_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zubotfx7ETcOn_3QHGnjqHlXbaKdtXb
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("single_genre_artists.csv")
df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df = df.drop(columns=['name_song','name_artists','id_songs'])

df.head()

import matplotlib.pyplot as plt
import seaborn as sns
df['danceability'].hist(bins = 30)

important_features = [
'danceability',
'energy',
'loudness',
'speechiness',
'acousticness',
'instrumentalness',
'liveness',
'valence',
'tempo',
'duration_ms'
]

df[important_features].hist(figsize=(14,10), bins=30)
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_features = scaler.fit_transform(df[important_features])

scaled_df = pd.DataFrame(scaled_features, columns=important_features)

scaled_df.head()

scaled_df = pd.DataFrame(scaled_features, columns=important_features)

scaled_df.head()

scaled_df.describe()

from sklearn.cluster import KMeans

inertia = []

for k in range(1,11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_df)
    inertia.append(kmeans.inertia_)

import matplotlib.pyplot as plt

plt.plot(range(1,11), inertia, marker='o')
plt.xlabel("Number of clusters (k)")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

for k in range(2,8):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(scaled_df)
    score = silhouette_score(scaled_df, labels)
    print(f"k = {k}, Silhouette Score = {score}")

kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(scaled_df)

df.head()

df['Cluster'].value_counts()

cluster_summary = df.groupby('Cluster')[[
'danceability',
'energy',
'loudness',
'speechiness',
'acousticness',
'instrumentalness',
'liveness',
'valence',
'tempo',
'duration_ms'
]].mean()

cluster_summary

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.heatmap(cluster_summary, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Cluster Feature Comparison Heatmap")
plt.show()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_summary = pd.DataFrame(
    scaler.fit_transform(cluster_summary),
    columns=cluster_summary.columns,
    index=cluster_summary.index
)

scaled_summary.plot(kind='bar', figsize=(12,6))
plt.title("Normalized Feature Comparison per Cluster")
plt.xticks(rotation=0)
plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_components = pca.fit_transform(scaled_df)

df['PCA1'] = pca_components[:,0]
df['PCA2'] = pca_components[:,1]

plt.figure(figsize=(8,6))
plt.scatter(df['PCA1'], df['PCA2'], c=df['Cluster'], cmap='viridis', alpha=0.5)
plt.xlabel("PCA1")
plt.ylabel("PCA2")
plt.title("Song Clusters Visualization")
plt.show()

cluster_names = {
0: "Acoustic / Chill",
1: "Party / Pop",
2: "Rap / Spoken"
}

df["Cluster_Label"] = df["Cluster"].map(cluster_names)

df.head()

from google.colab import files
files.download("clustered_songs.csv")